<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework> 
	<LangVersion>latest</LangVersion> 
	<AssemblyVersion></AssemblyVersion> 
	<FileVersion></FileVersion>
	<VersionPrefix>0.1.0</VersionPrefix>
	<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	<Platforms>AnyCPU;x64;ARM64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MattUtil">
      <HintPath>..\..\MattUtil\MattUtil\bin\x64\Release\MattUtil.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
